---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  'jest/globals': true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0